### ISSUE TITLE
Doesn't work after reboot

### ISSUE THREAD

**Issue by PeteEdley-EdleyIT** [ej52/proxmox-scripts#106]
If I reboot the container or the server, then the manger is no longer running,  I have to re-run wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/setup.sh | sh in order to get it running again.  Once it has finished running all is ok again untill i need to reboot again.

**Comment by tteck** [comment]
Execute the following command within the LXC console: 
```
sed -i 's/^pid/#pid/' /usr/local/openresty/nginx/conf/nginx.conf
```

**Comment by johnnylocktang** [comment]
Having the exact same error.

Service npm status says its Running.

Can only see traffic on port 3000.

**Comment by ScottSucksAtProgramming** [comment]
Also putting my hand up for this one. I'm really grateful for the script, and @PeteEdley-EdleyIT 's fix does work. Unfortunately I don't know enough else to troubleshoot it on my own right now.

**Comment by johnnylocktang** [comment]
Yeah, can confirm that too. Re-running makes it work. Will try to troubleshoot some tonight.

**Comment by ScottSucksAtProgramming** [comment]
Okay, I think I've fixed this for my install. 

When nginx starts up it looks to create `/run/nginx/nginx.pid` the directory is removed completely when the container restarts and nginx can't create the file. It might be a permissions issue I don't know, I'm really new at this.

If you `mkdir /run/nginx` and then start the process with `nginx` it starts up with no issues.
![Screenshot 2023-04-13 at 19 29 29](https://user-images.githubusercontent.com/89794691/231905790-91d664b7-11ab-4e59-9aae-37d9472f31e3.jpg)

I don't know what the deal with the `run/` directory is, but to fix this I changed the config for nginx to create the file in `/tmp/nginx/nginx.pid` and now it starts up happily when I restart the container.

### How I Fixed

1. Restart the container.
2. Edit the 3rd line in the `nginx.conf` for me it was `/etc/nginx/nginx.conf`

From:
 
![Screenshot 2023-04-13 at 19 48 51](https://user-images.githubusercontent.com/89794691/231906546-957a1a87-37f5-45fd-84c0-9da180d74d7c.jpg)

To:
![Screenshot 2023-04-13 at 19 50 40](https://user-images.githubusercontent.com/89794691/231906640-aa9c9edc-d39e-4260-b771-50e2c4813175.jpg)

3. Restart the container and confirm nginx is running.
![Screenshot 2023-04-13 at 19 52 41](https://user-images.githubusercontent.com/89794691/231906882-3195775e-ec06-41ca-bb38-40f508e0161e.jpg)

**Comment by ScottSucksAtProgramming** [comment]
It looks like this is due to the newest version of Nginx Proxy Manager 2.10.1 which was released about two weeks ago. I found a similar [issue here](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2795).

Might be able to fix the script by pulling an older version, but if anyone updates they'll end up with the same issue. If the script can update `nginx.conf` that might fix it. I don't know enough right now to update the script, or figure out another solution (it looks like changing the permissions of `/run` is bad news bears).

**Comment by dem36rus** [comment]
same problem

**Comment by Jamyz** [comment]
Thanks @ScottSucksAtProgramming , now works with the latest. Because comeback to latest 2.9.x fail with the same error s6 timeout.
But i see logs and i have lots of lines like :
`nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:81 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:81 failed (98: Address already in use)`

I dont no what is this.....

**Comment by rpgdev** [comment]
> Okay, I think I've fixed this for my install.
> 
> When nginx starts up it looks to create `/run/nginx/nginx.pid` the directory is removed completely when the container restarts and nginx can't create the file. It might be a permissions issue I don't know, I'm really new at this.
> 
> If you `mkdir /run/nginx` and then start the process with `nginx` it starts up with no issues. ![Screenshot 2023-04-13 at 19 29 29](https://user-images.githubusercontent.com/89794691/231905790-91d664b7-11ab-4e59-9aae-37d9472f31e3.jpg)
> 
> I don't know what the deal with the `run/` directory is, but to fix this I changed the config for nginx to create the file in `/tmp/nginx/nginx.pid` and now it starts up happily when I restart the container.
> ### How I Fixed
> 
>     1. Restart the container.
> 
>     2. Edit the 3rd line in the `nginx.conf` for me it was `/etc/nginx/nginx.conf`
> 
> 
> From:
> 
> ![Screenshot 2023-04-13 at 19 48 51](https://user-images.githubusercontent.com/89794691/231906546-957a1a87-37f5-45fd-84c0-9da180d74d7c.jpg)
> 
> To: ![Screenshot 2023-04-13 at 19 50 40](https://user-images.githubusercontent.com/89794691/231906640-aa9c9edc-d39e-4260-b771-50e2c4813175.jpg)
> 
>     3. Restart the container and confirm nginx is running.
>        ![Screenshot 2023-04-13 at 19 52 41](https://user-images.githubusercontent.com/89794691/231906882-3195775e-ec06-41ca-bb38-40f508e0161e.jpg)

Looks like it's working on my end. The fix is genius. Thank you!
