### ISSUE TITLE
When updating to version 2.10.1, it does not start 

### ISSUE THREAD

**Issue by vshaev** [ej52/proxmox-scripts#109]
**Script**
nginx-proxy-manager

**Describe the bug**
When updating to version 2.10.1, it does not start ...

**System info:**
 - Proxmox Version: [7.4-3]
 - Debian Version:11

![2023-04-04_12-37-58](https://user-images.githubusercontent.com/23740206/229755004-b52ddbf2-e4e6-43b3-abd0-b59e8ea5f472.png)

**Comment by Jetro97** [comment]
Same here. WebUI loads and display older v.2.9.19. Impossible to upgrade

**Comment by cascha42** [comment]
Same here, the openresty does not start. Any Ideas?

**Comment by irresisti** [comment]
Same here it does not start. Also cannot start manually 

`root@RevProxy:~# /lib/systemd/system/openresty.service
-bash: /lib/systemd/system/openresty.service: Permission denied`

**Comment by vmbs** [comment]
Same for me

<img width="577" alt="image" src="https://user-images.githubusercontent.com/69588689/231461104-dd936e54-da0a-49c9-b00a-ab0e0520c7ba.png">

**Comment by dhzl84** [comment]
Was digging a bit and made 2.10.1 start in my Debian 11 LXC.

`/usr/local/openresty/nginx/conf/nginx.conf` defines the pid file location `pid /run/nginx/nginx.pid;` but in `/lib/systemd/system/openresty.service` it is set to `/usr/local/openresty/nginx/logs/nginx.pid` which does not exist.

I changed the pid location in `/usr/local/openresty/nginx/conf/nginx.conf` to `pid /usr/local/openresty/nginx/logs/nginx.pid;`.

If this is a viable solution we could add this command to the debian `setup.sh`:
`sed -i -e 's/pid \/run\/nginx\/nginx.pid;/pid \/usr\/local\/openresty\/nginx\/logs\/nginx.pid;/g' /usr/local/openresty/nginx/conf/nginx.conf`

Be aware I'm neither a Linux expert nor do I have experience with openresty or nginx, so I do not know how this issue was introduced and if my fix is appropriate.

**Comment by vmbs** [comment]
Steps that are working for me, let's try modifying the nginx configuration to disable the use of a PID file:

Open the nginx configuration file:

`sudo nano /usr/local/openresty/nginx/conf/nginx.conf
`
Locate the line that contains the pid directive. It should look like this:

`pid /usr/local/openresty/nginx/logs/nginx.pid;
`
Comment out this line by adding a # at the beginning of the line:

`# pid /usr/local/openresty/nginx/logs/nginx.pid;`
Save the changes and exit the editor.

Test the nginx configuration:

`sudo /usr/local/openresty/nginx/sbin/nginx -t
`
If the configuration test is successful, proceed to the next step. Output from my tests:

```
nginx: the configuration file /usr/local/openresty/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test is successful
```

Restart the OpenResty service:

`sudo systemctl restart openresty.service
`
Check the status of the OpenResty service again:

`sudo systemctl status openresty.service
`
For me now is working.

**Comment by exquisite88** [comment]
> Was digging a bit and made 2.10.1 start in my Debian 11 LXC.
> 
> `/usr/local/openresty/nginx/conf/nginx.conf` defines the pid file location `pid /run/nginx/nginx.pid;` but in `/lib/systemd/system/openresty.service` it is set to `/usr/local/openresty/nginx/logs/nginx.pid` which does not exist.
> 
> I changed the pid location in `/usr/local/openresty/nginx/conf/nginx.conf` to `pid /usr/local/openresty/nginx/logs/nginx.pid;`.
> 
> If this is a viable solution we could add this command to the debian `setup.sh`: `sed -i -e 's/pid \/run\/nginx\/nginx.pid;/pid \/usr\/local\/openresty\/nginx\/logs\/nginx.pid;/g' /usr/local/openresty/nginx/conf/nginx.conf`
> 
> Be aware I'm neither a Linux expert nor do I have experience with openresty or nginx, so I do not know how this issue was introduced and if my fix is appropriate.

Did this and when the LXC had rebooted i got to the login screen.
But when i tried to login i got an error message saying "Bad Gateway"

Any ideas?
