### ISSUE TITLE
yarn cannot build

### ISSUE THREAD

**Issue by Na0mir** [ej52/proxmox-scripts#8]
Hello !

I'm trying to use your setup.sh script (after creating an alpine container with your create.sh) but looks like stuck at the step "Building frontend...".
I tried to manually run `yarn install` (works good) but command `yarn build` failed with this error:

> /app/frontend # yarn build
> yarn run v1.22.4
> error Command "build" not found.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

yarn seems well installed :
`apk list --installed | grep "yarn"` 
gives me 
> yarn-1.22.4-r0 x86_64 {yarn} (BSD-2-Clause) [installed]

Any idea why ?

EDIT: I added 2 screenshots, 1st is normal script as is > stuck somewhere and the container is deleted automatically.. that's why I split it in 2.
2nd is when I try to use `yarn build` manually after stuck.
![2021-03-03 17_14_11-proxmox - Proxmox Console](https://user-images.githubusercontent.com/6453724/109785889-8f156b80-7c47-11eb-9540-ae234ce7b263.png)
![2021-03-03 17_38_54-proxmox - Proxmox Console](https://user-images.githubusercontent.com/6453724/109785900-92105c00-7c47-11eb-9776-450958efcaf8.png)

**Comment by ej52** [comment]
What version of alpine are you running?
Seems to me like there is an issue with changing to the build directory in the script on your CT.

You are getting the error when manually running `yarn build` because **package.json** does not exist in `/app/frontend`
The build happens in a `/tmp` directory and copies the frontend files over to `/app/frontend`

After running `setup.sh` and it fails at build, you can check to see if there is a folder like `/tmp/tmp.XXXXXX` which contains **package.json** and run `yarn build` in there to see if it works.

**Comment by Na0mir** [comment]
My Alpine version is 3.12.4, indeed the tmp folder are correctly created in /tmp/tmp.xxxxx and I did not used the command in the right folder :(
I removed some code to have more details about the operations...
I tried multiple times, error is always different:
[npm-fail.txt](https://github.com/ej52/proxmox-scripts/files/6081190/npm-fail.txt)
[npm-fail-2.txt](https://github.com/ej52/proxmox-scripts/files/6081188/npm-fail-2.txt)

Finally it started to work by himself after multiple times, I don't know why.
I guess now it works I will never update it, or at least snapshot before and execute the script multiple time
Thanks for the help and the script!
